openapi: '3.0.0'
info:
  title: Data scrapper Admin API
  version: '1.0'
servers:
  - url: https://localhost/v1
components:
  schemas:
    GeneralErrors:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    User:
      type: object
      properties:
        name:
          type: string
        login:
          type: string
        password:
          type: string
    CreatedUser:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    CreatedWebResource:
      type: object
      properties:
        resourceId: 
          type: string
        url:
          type: string
        dataSchema:
          type: object
          $ref: "#/components/schemas/WebResource"
    WebResource:
      type: object
      properties:
        Url:
          type: string
        Content:
          type: string
        GameCountryAndDate:
          type: object
          $ref: "#/components/schemas/WebResourceItemGroup"
        GameData:
          type: object
          $ref: "#/components/schemas/WebResourceItem"
    WebResourceItemGroup:
      type: object
      properties:
        HeadDivClass:
          type: object
          $ref: "#/components/schemas/WebResourceSelector"
        GameDataSelector:
          type: array
          items:
            type: object
            $ref: "#/components/schemas/WebResourceSelectorDescriptor"
        GameCountrySelector:
          type: array
          items:
            type: object
            $ref: "#/components/schemas/WebResourceSelectorDescriptor"
        GameLeagueSelector:
          type: array
          items:
            type: object
            $ref: "#/components/schemas/WebResourceSelectorDescriptor"
    WebResourceItem:
      type: object
      properties:
        RowDivClass:
          type: object
          $ref: "#/components/schemas/WebResourceSelector"
        GameTime:
          type: object
          $ref: "#/components/schemas/WebResourceSelector"
        FirstTeam:
          type: object
          $ref: "#/components/schemas/WebResourceSelector"
        SecondTeam:
          type: object
          $ref: "#/components/schemas/WebResourceSelector"
        GameScore:
          type: array
          items:
            type: object
            $ref: "#/components/schemas/WebResourceSelectorDescriptor"
    WebResourceSelector:
      type: string      
    WebResourceSelectorDescriptor:
      type: object
      properties:
        selector:
          $ref: "#/components/schemas/WebResourceSelector"
        order:
          type: string    
paths:
  /user:
    post:
      description: "Creates a new user with provided details"
      summary: "Uses details in request bodyto create a new user"
      operationId: "CreateUser"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        '201':
          description: "User created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreatedUser"
        '400':
          description: "Request has errors"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeneralErrors"
        '401':
          description: "User not authorized"
        '409':
          description: "User with the same name already exists"
  /user/{userId}:
    patch:
      description: "Update regstered user"
      summary: "Updates User details" 
      operationId: "UpdateUser"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        '200':
          description: "Updated"
        '401':
          description: "User is not authorized"
        '404':
          description: "Do not exist"
        '409':
          description: "User already exist"
    get:
      description: 
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreatedUser"
        '401':
          description: "User not authorized"
        '404':
          description: "Do not exist"
    parameters:
    - name: userId
      in: path
      description: "Registered User's id"
      required: true
      schema:
        type: string
  /schema:
    post:
      description: "Regster public web resource data schema"
      summary: "Reqister a schema data scraper will use to collect data from public web resource"
      operationId: "CreatePublicWebResouceDataSchema"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/WebResource"
      responses:
        '201':
          description: "Data Schema successfully created"
        '400':
          description: "Request has errors"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeneralErrors"
        '401':
          description: "User not authorized"
        '409':
          description: "Data Schema for provided web resource already registered"
  /schema/{schemaId}:
    patch:
      description: "Update regstered schema"
      summary: "Updates schema details" 
      operationId: "UpdateSchema"
      responses:
        '200':
          description: "Updated"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreatedWebResource"
        '400':
          description: "Request has errors"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeneralErrors"
        '401':
          description: "User is not authorized"
        '404':
          description: "Do not exist"
    get:
      description: 
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreatedWebResource"
        '401':
          description: "User not authorized"
        '404':
          description: "Do not exist"
    parameters:
    - name: schemaId
      in: path
      description: "Registered Schema's id"
      required: true
      schema:
        type: string
  /schedule/{schemaId}:
    post:
      description: "Schedule reqistered web resource for the scap"
      summary: "Schedule registered web resource for the scpap, as a paramerter provides CRON expression to define desired scrapping schedule"
      operationId: "ScheduleScaper"
      responses:
        '201':
          description: "Scaper created"
        '400':
          description: "Request has errors"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeneralErrors"
        '401':
          description: "User not authorized"
        '409':
          description: "Scaper already exists"
    patch:
      description: "Update regstered scraper"
      summary: "Updates scaper details" 
      operationId: "UpdateScaper"
      responses:
        '200':
          description: "Updated"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreatedWebResource"
        '400':
          description: "Request has errors"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeneralErrors"
        '401':
          description: "User is not authorized"
        '404':
          description: "Do not exist"
    get:
      description: 
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreatedWebResource"
        '401':
          description: "User not authorized"
        '404':
          description: "Do not exist"
    parameters:
    - name: schemaId
      in: path
      description: "Registered Schema's id" 
      required: true
      schema:
        type: string
